[workspace]
members     = [
    "svg",
    "svgflo",
]
resolver    = "2"

[patch.crates-io]
flo_binding             = { git = "https://github.com/Logicalshift/flo_binding", branch = "v3.0" }
flo_scene               = { git = "https://github.com/Logicalshift/flo_scene", branch = "v0.3" }
flo_scene_guest         = { git = "https://github.com/Logicalshift/flo_scene", branch = "v0.3" }

flo_draw                = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_canvas              = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_canvas_events       = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_render              = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_render_canvas       = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_render_gl_offscreen = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }
flo_render_software     = { git = "https://github.com/Logicalshift/flo_draw", branch = "v0.4" }

flo_svg                 = { path = "svg" }
svgflo                  = { path = "svgflo" }

# flo_canvas              = { path = "../flo_draw/canvas" }
# flo_render              = { path = "../flo_draw/render" }
# flo_render_canvas       = { path = "../flo_draw/render_canvas" }
# flo_render_gl_offscreen = { path = "../flo_draw/render_gl_offscreen" }
# flo_draw                = { path = "../flo_draw/draw" }
